# Generated by Django 4.2.27 on 2026-01-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('error', 'error')], default='queued', max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(default='small', max_length=32)),
                ('segment_sec', models.PositiveIntegerField(default=600)),
                ('language', models.CharField(default='ja', max_length=8)),
                ('input_file', models.FileField(upload_to='input/')),
                ('output_text', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
