# Generated by Django 4.2.27 on 2026-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='diarize',
            field=models.BooleanField(default=True),
        ),
    ]
