# Generated by Django 4.2.27 on 2026-02-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='r2_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='language',
            field=models.CharField(default='auto', max_length=8),
        ),
    ]
