# Generated by Django 4.2.27 on 2026-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0002_transcriptionjob_diarize'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
